version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - api
    environment:
      MYSQL_ROOT_PASSWORD: pass
  restful-api-laravel:
    image: restful-api-laravel
    container_name: restful-api-laravel
    depends_on:
      - mysql
    ports:
      - 8000:8000
    networks:
      - api
    environment:
      DB_HOST: mysql
      L5_SWAGGER_GENERATE_ALWAYS: false
networks:
  api: